### ISSUE TITLE
Request for GPT-2 models trained on impossible languages

### ISSUE THREAD

**Issue by y1ny** [jkallini/mission-impossible-language-models#1]
Hi, excellent work! I'm interested in testing a few sentences with the GPT-2 models trained on the impossible languages. Have you considered uploading the models? While I see that you've provided the training scripts, training the models from scratch, as you mentioned in Appendix B, is quite time-consuming.

**Comment by stevenwalton** [comment]
I am also interested. Did you also happen to have wandb logs (I know mistral includes wandb logging in their training script)?

**Comment by chunhuizng** [comment]
I am interested too! That would be very helpful

**Comment by jkallini** [comment]
Hi all! We're releasing the models we trained for the paper here: https://huggingface.co/mission-impossible-lms
For each of the 15 languages in the paper, we're releasing a GPT-2 Small model and GPT-2 Small model without positional encodings. And for each model, we're releasing 30 checkpoints!
These are the models for one of the random seeds from the paper.
