### ISSUE TITLE
which base model of GPT 2 small is being used?

### ISSUE THREAD

**Issue by z050209** [jkallini/mission-impossible-language-models#3]
Dear team, 
I have another question regarding to the model training, were you using the model from https://github.com/stanford-crfm/mistral? do you train the model from scratch?

Thanks. 

<img width="322" alt="image" src="https://github.com/user-attachments/assets/41e737d9-251a-4755-8615-ac0ba2f2d5fd">

**Comment by jkallini** [comment]
Hi! Thanks for the question!
We trained all GPT-2 Small models from scratch. The model class is `GPT2LMHeadModel` from HuggingFace.
